require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'GSPApp',
'Development' => :debug,
'Development.Release' => :release,
'Staging' => :debug,
'Staging.Release' => :release

target 'GSPApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'GSPAppTests' do
    inherit! :complete
    # Pods for testing
  end

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Auth'
pod 'naveridlogin-sdk-ios'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'GSPApp-tvOS' do
  # Pods for GSPApp-tvOS

  target 'GSPApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
