require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

project 'ddangkong',
'Development' => :debug,
'Development.Release' => :release,
'Staging' => :debug,
'Staging.Release' => :release

target 'ddangkong' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone"
  pod 'RNIap', :path => '../node_modules/react-native-iap'

  target 'ddangkongTests' do
    inherit! :complete
    # Pods for testing
  end

pod 'naveridlogin-sdk-ios'

pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Auth'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ddangkong-tvOS' do
  # Pods for ddangkong-tvOS

  target 'ddangkong-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
